openapi: "3.0.3"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1
  - url: http://localhost:4000
paths:
  /support/tickets:
    post:
      summary: Create support ticket
      description: Create support ticket with detailed informations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                  example: "customer_123"
                issue:
                  type: string
                  example: "Không thể đăng nhập vào tài khoản"
                priority:
                  type: string
                  example: "high"
              required:
                - customerId
                - issue
                - priority
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "ticket_123"
                  customerId:
                    type: string
                    example: "customer_123"
                  issue:
                    type: string
                    example: "Không thể đăng nhập vào tài khoản"
                  priority:
                    type: string
                    example: "high"
                  status:
                    type: string
                    example: "open"
        "400":
          description: Failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input"
