openapi: "3.0.3"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1
  - url: http://localhost:4000
paths:
  /promocode:
    post:
      summary: Create promo code
      description: Create a new promo code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                PromoCode_ID:
                  type: string
                  example: "PROMO123"
                Code:
                  type: string
                  example: "DISCOUNT10"
                DiscountAmount:
                  type: number
                  format: double
                  example: 10.0
                StartDate:
                  type: string
                  format: date-time
                  example: "2024-01-01T00:00:00Z"
                EndDate:
                  type: string
                  format: date-time
                  example: "2024-12-31T23:59:59Z"
                CampaignID:
                  type: string
                  example: "CAM123"
              required:
                - Code
                - DiscountAmount
                - StartDate
                - EndDate
      responses:
        "201":
          description: Promo code created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  PromoCode_ID:
                    type: string
                    example: "PROMO123"
    get:
      summary: Get list of promo codes
      description: Retrieve a list of all promo codes
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    PromoCode_ID:
                      type: string
                      example: "PROMO123"
                    Code:
                      type: string
                      example: "DISCOUNT10"
                    DiscountAmount:
                      type: number
                      format: double
                      example: 10.0
                    StartDate:
                      type: string
                      format: date-time
                      example: "2024-01-01T00:00:00Z"
                    EndDate:
                      type: string
                      format: date-time
                      example: "2024-12-31T23:59:59Z"
                    CampaignID:
                      type: string
                      example: "CAM123"
  /promocode/{PromoCode_ID}:
    put:
      summary: Update promo code
      description: Update an existing promo code
      parameters:
        - in: path
          name: PromoCode_ID
          required: true
          schema:
            type: string
            example: "PROMO123"
          description: ID of the promo code to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Code:
                  type: string
                  example: "DISCOUNT10"
                DiscountAmount:
                  type: number
                  format: double
                  example: 10.0
                StartDate:
                  type: string
                  format: date-time
                  example: "2024-01-01T00:00:00Z"
                EndDate:
                  type: string
                  format: date-time
                  example: "2024-12-31T23:59:59Z"
                CampaignID:
                  type: string
                  example: "CAM123"
      responses:
        "200":
          description: Promo code updated successfully
    delete:
      summary: Delete promo code
      description: Delete an existing promo code
      parameters:
        - in: path
          name: PromoCode_ID
          required: true
          schema:
            type: string
            example: "PROMO123"
          description: ID of the promo code to delete
      responses:
        "204":
          description: Promo code deleted successfully
