openapi: "3.0.3"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:3306
paths:
  /role:
    post:
      summary: Create role
      description: Create a new role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Role_ID:
                  type: string
                  example: "ROLE123"
                RoleName:
                  type: string
                  example: "Admin"
              required:
                - RoleName
      responses:
        "201":
          description: Role created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  Role_ID:
                    type: string
                    example: "ROLE123"
    get:
      summary: Get list of roles
      description: Retrieve a list of all roles
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Role_ID:
                      type: string
                      example: "ROLE123"
                    RoleName:
                      type: string
                      example: "Admin"
  /role/{Role_ID}:
    put:
      summary: Update role
      description: Update an existing role
      parameters:
        - in: path
          name: Role_ID
          required: true
          schema:
            type: string
            example: "ROLE123"
          description: ID of the role to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RoleName:
                  type: string
                  example: "Updated Admin"
      responses:
        "200":
          description: Role updated successfully
    delete:
      summary: Delete role
      description: Delete an existing role
      parameters:
        - in: path
          name: Role_ID
          required: true
          schema:
            type: string
            example: "ROLE123"
          description: ID of the role to delete
      responses:
        "204":
          description: Role deleted successfully
